# Generated by Django 5.0.6 on 2024-05-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_fotografia', models.CharField(default='https://objetivoligar.com/wp-content/uploads/2017/03/blank-profile-picture-973460_1280-580x580.jpg', max_length=255)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=9)),
                ('sexo', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('id_tipo_usuario', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
