# Generated by Django 4.2.4 on 2024-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_fotografia', models.ImageField(default='https://objetivoligar.com/wp-content/uploads/2017/03/blank-profile-picture-973460_1280-580x580.jpg', max_length=255, upload_to='')),
                ('nombres', models.CharField(blank=True, max_length=50)),
                ('apellido_paterno', models.CharField(blank=True, max_length=30)),
                ('apellido_materno', models.CharField(blank=True, max_length=30)),
                ('dni', models.CharField(blank=True, max_length=8, unique=True)),
                ('celular', models.CharField(blank=True, max_length=9)),
                ('domicilio', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
