# Generated by Django 5.0.6 on 2024-05-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='departamento',
            field=models.CharField(default='hola', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='distrito',
            field=models.CharField(default='holaaa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='provincia',
            field=models.CharField(default='holaaaaaaa', max_length=50),
            preserve_default=False,
        ),
    ]
