# Generated by Django 4.2.4 on 2024-05-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='ruta_fotografia',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
