# Generated by Django 4.2.4 on 2024-05-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_usuarios_ruta_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ruta_fotografia',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
